from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "data/processed/gold_context_trades"
OUTPUTS_DIR = ROOT / "outputs"

PREV_SESSIONS = OUT_DIR / "frame_data_video_session_maps_v0_1.csv"
PREV_TRADES = OUT_DIR / "frame_data_trade_context_queue_v0_1.csv"
PREV_RULES = OUT_DIR / "frame_data_rule_seed_queue_v0_1.csv"

OUT_SESSIONS = OUT_DIR / "frame_data_video_session_maps_v0_2.csv"
OUT_TRADES = OUT_DIR / "frame_data_trade_context_queue_v0_2.csv"
OUT_RULES = OUT_DIR / "frame_data_rule_seed_queue_v0_2.csv"
OUT_SUMMARY = OUTPUTS_DIR / "frame_data_validated_batch_scope16_17_summary.md"


def read_csv(path: Path) -> tuple[list[str], list[dict[str, str]]]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return list(reader.fieldnames or []), list(reader)


def write_csv(path: Path, fields: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def frame(video_id: str, name: str) -> str:
    return (
        Path("data/source/craig_frames/browser_review")
        / f"{video_id}_frame_data_pass"
        / name
    ).as_posix()


def frames(video_id: str, names: list[str]) -> str:
    return "|".join(frame(video_id, name) for name in names)


def trade(
    context_id: str,
    video_id: str,
    scope_order: str,
    sequence: int,
    decision_type: str,
    gold_status: str,
    symbol: str,
    direction: str,
    market_date: str,
    market_window: str,
    confidence: str,
    youtube_window: str,
    anchors: str,
    entry: str,
    stop: str,
    target: str,
    result: str,
    risk_result: str,
    pre: str,
    setup: str,
    entry_plan: str,
    management: str,
    exit_result: str,
    evidence: str,
    ohlcv: str,
    rule_notes: str,
    uncertainty: str,
) -> dict[str, str]:
    return {
        "context_id": context_id,
        "video_id": video_id,
        "scope_order": scope_order,
        "sequence_in_video": str(sequence),
        "decision_type": decision_type,
        "gold_status": gold_status,
        "symbol": symbol,
        "direction": direction,
        "chart_timeframe": "1m",
        "market_date_utc_minus4": market_date,
        "market_time_window_utc_minus4": market_window,
        "market_time_confidence": confidence,
        "youtube_window": youtube_window,
        "youtube_anchor_sec": anchors,
        "entry_price": entry,
        "stop_price": stop,
        "target_price": target,
        "realized_result": result,
        "risk_management_result": risk_result,
        "pre_trade_context_ko": pre,
        "setup_context_ko": setup,
        "entry_plan_ko": entry_plan,
        "management_ko": management,
        "exit_result_ko": exit_result,
        "frame_evidence_paths": evidence,
        "ohlcv_alignment_ko": ohlcv,
        "rule_extraction_notes_ko": rule_notes,
        "remaining_uncertainty_ko": uncertainty,
    }


def rule(
    rule_seed_id: str,
    context_id: str,
    family: str,
    market_filter: str,
    trigger: str,
    entry_seed: str,
    invalidation: str,
    management: str,
    tp: str,
    avoid: str,
    features: str,
    strength: str,
) -> dict[str, str]:
    return {
        "rule_seed_id": rule_seed_id,
        "context_id": context_id,
        "rule_family": family,
        "market_state_filter_ko": market_filter,
        "setup_trigger_ko": trigger,
        "entry_rule_seed_ko": entry_seed,
        "invalidation_rule_seed_ko": invalidation,
        "management_rule_seed_ko": management,
        "take_profit_rule_seed_ko": tp,
        "do_not_trade_or_exit_rule_seed_ko": avoid,
        "quant_features_to_measure": features,
        "source_strength": strength,
    }


def main() -> None:
    session_fields, sessions = read_csv(PREV_SESSIONS)
    trade_fields, trades = read_csv(PREV_TRADES)
    rule_fields, rules = read_csv(PREV_RULES)

    sessions.extend(
        [
            {
                "session_context_id": "p47HZv1fcUM_session_01",
                "video_id": "p47HZv1fcUM",
                "scope_order": "16",
                "video_title": "Live Day Trading (I DID NOT EXPECT TO WIN)",
                "processed_status": "frame_plus_ohlcv_validated_second_pass",
                "market_dates_utc_minus4": "2025-04-09 SOL session; FOMC/tariff volatility day",
                "primary_symbols": "SOLUSDT",
                "confirmed_timeframes": "TradingView 1m chart visible in setup and recap frames; session overlays include 2:50 PM, 5:30 PM, 11:00 PM.",
                "session_map_ko": (
                    "하루 risk는 $500/trade, 목표는 $4,000. 초반 daily bias는 tariff 이슈와 FOMC 때문에 bearish/volatile로 두되, "
                    "NY 09:30 open 이후 실제 displacement 방향을 먼저 본다. 오전에는 SOL long으로 시작해 trend가 살아 있는 동안 runner를 노리다가 "
                    "trend touch/weakness에서 2.5R을 확정한다. 그 직후 같은 trend break를 short로 뒤집지만 market이 calm하고 bullish가 살아 있어 BE로 나온다. "
                    "오후 tariff/FOMC성 급등 뒤에는 exposure 욕구와 fat-finger execution anomaly가 섞이고, 이후 trend break/FVG short와 gym 전 long loss를 거친다. "
                    "마지막 11 PM 부근에는 support-turned-resistance와 sell signal로 SOL short를 잡아 equal lows 아래에서 6R가량을 확정한다."
                ),
                "strategy_map_ko": (
                    "이 영상의 핵심은 volatile news day에서도 Craig가 '예측'보다 'reaction after displacement'를 우선한다는 점이다. "
                    "FVG midpoint/zone, prior support/resistance flip, trendline break/retest, CHoCH/sell signal을 조합하고, "
                    "초기 반응 후 key level close가 나오면 risk를 BE 또는 profit 안쪽으로 옮긴다. 다만 큰 move를 노리기 위해 1:4 도달 후에도 일부 risk를 남기는 tactical decision이 관찰된다."
                ),
                "data_used_ko": "SOLUSDT 1m 2025-04-09 NY cache. Video frames captured from logged-in YouTube playback.",
                "frame_method_ko": (
                    "영상 전체를 프레임화하지 않고, setup explanation, position box, risk-reduction moment, exit/recap만 timestamp URL로 이동해 캡처했다. "
                    "말과 프레임이 겹치는 곳은 OHLCV로 actual UTC-4 window를 좁혔다."
                ),
                "frame_contact_sheet": frame("p47HZv1fcUM", "p47HZv1fcUM_frame_data_pass_contact_sheet.jpg"),
                "remaining_uncertainty_ko": "일부 운동/휴식 중 trade는 live chart가 흐릿해 price box exact OCR 대신 recap + 1m 구조 정렬로 기록한다.",
            },
            {
                "session_context_id": "mNnqjq8BzeA_session_01",
                "video_id": "mNnqjq8BzeA",
                "scope_order": "17",
                "video_title": "Live Day Trading (THIS DAY WAS BORING BUT WORKED)",
                "processed_status": "frame_plus_ohlcv_validated_second_pass",
                "market_dates_utc_minus4": "2025-04-30 session; 2025-05-01 SOL overnight continuation for final trade",
                "primary_symbols": "SOLUSDT, ETHUSDT",
                "confirmed_timeframes": "TradingView 1m visible in trade frames; 4h used for daily support/resistance bias at session setup.",
                "session_map_ko": (
                    "시작은 9:30, risk $500/trade, goal $4,000. 4h에서 prior support/resistance underside를 daily bias context로 잡고, "
                    "Core PCE/personal income/spending news를 high-impact event로 체크한다. 오전에는 SOL long win, SOL short small win, SOL short loss로 방어적으로 진행한다. "
                    "오후에는 ETH로 전환해 long BE, short small win, resistance short win, ETH long 5.7R win을 만든다. 마지막에는 SOL uptrend 약화 short를 overnight으로 남겼으나 거의 target에 닿고 되돌아와 BE로 종료한다."
                ),
                "strategy_map_ko": (
                    "이 영상은 'boring/choppy day에서도 risk를 계속 줄이며 큰 한 방을 기다리는' 샘플이다. "
                    "FVG midpoint, CHoCH, trend break, HTF SR, prior low/support-to-resistance, volume fading, equal lows target을 반복 사용한다. "
                    "수익이 빠르게 나오면 일부 실현 또는 BE 이동을 하고, 방향 follow-through가 없으면 small win/BE로 끊어 capital preservation을 우선한다."
                ),
                "data_used_ko": "SOLUSDT/ETHUSDT 1m 2025-04-30 NY cache; SOLUSDT 1m 2025-05-01 NY cache added for overnight result check.",
                "frame_method_ko": (
                    "8개 decision unit 각각 setup/management/recap 중 최소 1개 프레임을 확보했다. "
                    "frame price, visible overlay time, recap journal, 1m OHLCV를 함께 사용해 symbol/time/direction을 재확인했다."
                ),
                "frame_contact_sheet": frame("mNnqjq8BzeA", "mNnqjq8BzeA_frame_data_pass_contact_sheet.jpg"),
                "remaining_uncertainty_ko": "일부 exact entry/SL/TP 숫자는 프레임상 작아 about 값으로 기록한다. 구조/결과/management는 recap과 데이터로 충분히 확보됨.",
            },
        ]
    )

    p47 = "p47HZv1fcUM"
    mnn = "mNnqjq8BzeA"

    trades.extend(
        [
            trade(
                "p47HZv1fcUM_fd_01_trade1_sol_long_news_open_win",
                p47,
                "16",
                1,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "long",
                "2025-04-09",
                "09:32-10:42",
                "medium_visible_frame_price_plus_ohlcv",
                "04:04-10:42 + recap 21:38",
                "244|285|372|448|607|642|1298",
                "about 104.8-105.0",
                "about 104.2",
                "about 109.5 / 2.618 extension runner plan",
                "+about $1,500 / 2.5R",
                "Risk was reduced to BE after close over recent high, then locked to 1R and later 2.58R under swing low before trend break exit.",
                "Tariff/FOMC volatility day라 daily bias는 bearish지만, Craig는 09:30 open 직후 시장이 어느 방향으로 반응하는지 먼저 보겠다고 했다. 초반 SOL이 morning downtrend를 만들다가 NY open에서 큰 displacement로 level을 돌파했다.",
                "저항으로 여러 번 맞던 trend/level을 위로 깨고, 그 돌파 캔들이 남긴 FVG가 다시 support/overside retest가 되는 구조. 그는 이 FVG와 trend retest, 그리고 추가 indicator confluence를 entry 근거로 설명했다.",
                "Position calculator로 fixed $500 risk long. FVG/support zone 재방문에서 entry를 잡고, 위쪽 1:4 및 2.618 extension 가능성을 보되 처음부터 전부 확정 TP로 보지는 않았다.",
                "처음에는 recent high close 후 BE로 줄였고, 1:4가 도달해도 큰 뉴스 momentum을 노리기 위해 너무 빨리 crowd하지 않았다. 이후 trendline을 더 자주 touch하며 약해지자 swing low 아래로 stop을 올려 2.58R을 확보했다.",
                "Trend level이 결국 깨지며 stop/exit. 그는 tariff delay news가 없었다면 이 판단이 맞았을 수 있지만, 결과적으로 더 들고 있었다면 11R까지 갔을 것이라 리뷰했다.",
                frames(
                    p47,
                    [
                        "0244_trade1_open_sol_long_risk_zero_position.png",
                        "0285_trade1_ny_open_displacement_fvg_retest.png",
                        "0372_trade1_five_wave_fib_context.png",
                        "0448_trade1_one_to_four_reduce_risk_choice.png",
                        "0607_trade1_trend_touches_lock_2_58r.png",
                        "0642_trade1_exit_trade2_short_possible.png",
                        "1298_recap_trade1.png",
                    ],
                ),
                "SOL 09:31-09:32에 104.36->106.40까지 strong displacement, 09:37 low 104.35 retest 후 10:33 high 107.40. 10:35 이후 weakness/chop이 생겨 trend-break exit narrative와 맞다.",
                "Volatile bearish macro day여도 NY open displacement가 prior resistance를 break하고 FVG support retest가 생기면 counter long 가능. 단, runner 욕심은 trendline contact frequency와 swing-low trail로 관리한다.",
                "정확한 entry/SL/TP 숫자는 프레임에서 about로만 읽힘. 결과와 risk management는 recap에서 강함.",
            ),
            trade(
                "p47HZv1fcUM_fd_02_trade2_sol_short_underside_be",
                p47,
                "16",
                2,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-09",
                "10:42-13:20",
                "medium_transcript_ohlcv_alignment",
                "10:42-13:22",
                "642|671|776|802",
                "about 106.8-107.0",
                "above underside retest high",
                "lower blue level / downside continuation",
                "+$13 / effectively BE",
                "Reduced to BE after lower levels broke; exited at entry when price pushed back up and implied trend remained bullish.",
                "Trade1 exit 직후, 같은 trendline break가 short opportunity가 될 수 있다고 보았다. Market은 calm하고 volatility가 줄어 있어 momentum confirmation이 필요했다.",
                "여러 contact point를 만든 상승 trendline이 깨지고, 그 underside가 resistance + important FVG block으로 겹친다. 가격이 그 영역으로 되돌아와 poke 후 reject되는 것을 short 근거로 삼았다.",
                "Underside retest/FVG block에서 short. Blue lower level이 깨져야 risk를 줄일 수 있다고 사전에 말했다.",
                "초기 technical response가 나오자 lower level break 후 BE로 낮췄다. 그러나 new low follow-through가 안 나오고 다시 위로 push하면 bullish trend를 싸우지 않겠다고 했다.",
                "가격이 entry로 되돌아와 +$13으로 종료. Win으로 기록하지만 실질적으로 BE이며, 이후 lunch/scan으로 넘어갔다.",
                frames(
                    p47,
                    [
                        "0642_trade1_exit_trade2_short_possible.png",
                        "0671_trade2_underside_retest_fvg_short.png",
                        "0776_trade2_reduce_be_after_break.png",
                        "0802_trade2_be_exit_trend_still_bullish.png",
                    ],
                ),
                "SOL 10:50-13:00은 105.70 low에서 108.67 high로 천천히 올라가는 calm/chop 구간. Short가 큰 downside를 만들지 못하고 BE로 돌아온 설명과 부합한다.",
                "Trend break short는 underside retest + FVG block + lower level break가 있어야 한다. Initial response만으로 충분하지 않고, new low 실패 시 BE로 철수한다.",
                "시장 exact exit minute은 video/recap 기반. 가격 box exact OCR은 미확정.",
            ),
            trade(
                "p47HZv1fcUM_fd_03_trade3_sol_short_fatfinger_reentry_loss",
                p47,
                "16",
                3,
                "executed_trade_with_execution_anomaly",
                "gold_frame_data_context_ready_execution_anomaly_not_rule_core",
                "SOLUSDT",
                "short",
                "2025-04-09",
                "14:40-15:24",
                "high_visible_overlay_plus_ohlcv",
                "14:42-15:26 + recap 22:24",
                "882|926|1344",
                "critical retest level after tariff pump",
                "above retest/stop level",
                "afternoon selloff continuation",
                "+about $1,400 accidental first close; -$568 on intended second go",
                "First fill was oversized by duplicate order submissions and closed immediately; intended re-entry later stopped after sideways chop.",
                "FOMC/tariff news로 SOL이 급등해 아침 long을 계속 들고 있었다면 11R였을 상황. 그는 큰 움직임 뒤 바로 fill-down 되지 않을 수 있음을 알면서도 market exposure를 원했다.",
                "강한 pump 이후 critical level retest에서 short exposure를 잡으려 했다. 다만 스스로 'probably wasn't going to work'라고 recap에서 말해, quality가 낮거나 news-driven continuation이 우세한 setup임을 인정했다.",
                "원래는 retest entry에서 적정 size로 short를 잡고 afternoon selloff를 기대. 그러나 주문을 여러 번 제출해 너무 큰 size가 들어가 execution anomaly가 발생했다.",
                "과다 size를 본 즉시 전체 포지션을 닫아 $1.4k 정도를 잠금. 이후 intended order/re-entry는 그대로 두고 retest fill 후 정상 size로 진행했지만 sideways chop 끝에 stop.",
                "Recap: first accidental entry +$1,400, second go-round -$568. 이 행은 rule core로 쓰기보다 'exposure 욕구/저품질 setup/실행오류' 태그로 분리해야 한다.",
                frames(
                    p47,
                    [
                        "0882_trade3_fatfinger_position_oversized.png",
                        "0926_trade3_second_go_stopped_sideways.png",
                        "1344_recap_fatfinger_second_loss.png",
                    ],
                ),
                "SOL 13:19-14:25에 107.17 low에서 120.69 high까지 news pump. 14:42-15:30은 118-120대 sideways/retest 구간이라 short re-entry가 바로 실패하지 않고 오래 chop된 설명과 맞다.",
                "Rule model에서는 duplicate-size anomaly를 학습하지 말고 제외 태그. 다만 'news pump 후 immediate fade를 무리하게 기대하면 quality 낮음'이라는 negative example로는 유용하다.",
                "Entry/stop exact price는 흐릿함. Intent와 result는 transcript+recap에서 강함.",
            ),
            trade(
                "p47HZv1fcUM_fd_04_trade4_sol_short_afternoon_fvg_be",
                p47,
                "16",
                4,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-09",
                "17:30-18:15",
                "medium_visible_overlay_transcript_ohlcv",
                "16:08-17:18 + recap 22:42",
                "968|1008|1362",
                "afternoon underside/FVG zone",
                "above trend underside / almost stopped",
                "lower breakdown level",
                "BE after risk reduction",
                "Almost stopped, then price moved down enough to reduce to BE; later came back and tagged BE.",
                "Fat-finger sequence 후 trade number five를 찾으며 gym 전 하나를 잡아두고 싶어했다. 시장은 뉴스 급등 이후 오후 trend가 꺾일지 확인하는 구간이었다.",
                "SOL afternoon trend가 breakdown되며 FVG가 생기고, 그 FVG/underside trend retest가 short signal로 작동했다. 그는 level 아래 close가 나오면 risk-free로 만들 수 있다고 말했다.",
                "Breakdown FVG로 short. Price가 underside를 test하면서도 flip하면 downside momentum이 생길 수 있다고 봄.",
                "Risk reduction notice가 울리고, lower level 아래 close 후 stop을 low 근처/BE로 줄였다. 이후 큰 follow-through가 없어 BE에 가까운 결과로 종료.",
                "Recap에서는 CHoCH into gap entry, almost stop, reduce to BE, then price tags BE로 정리했다.",
                frames(
                    p47,
                    [
                        "0968_trade4_5_afternoon_trend_break_fvg.png",
                        "1008_trade4_5_risk_reduction_breakdown.png",
                        "1362_recap_afternoon_be_and_gym_loss.png",
                    ],
                ),
                "SOL 17:00-18:30은 120.45 high 후 118.93 low까지 흔들렸지만 지속 추세는 약함. Breakdown 반응 후 BE 되돌림이라는 설명과 맞다.",
                "Afternoon trend break short는 FVG + underside retest + lower-level close가 필요. Lower close 후 risk-free로 만들고, momentum이 없으면 BE를 받아들인다.",
                "Live risk-reduction frame은 흐림. Recap과 데이터 구조로 gold 유지.",
            ),
            trade(
                "p47HZv1fcUM_fd_05_trade5_sol_long_gym_loss",
                p47,
                "16",
                5,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "long",
                "2025-04-09",
                "18:10-18:55",
                "medium_transcript_recap_ohlcv",
                "18:14 + recap 22:42",
                "1094|1362",
                "FVG after significant push down",
                "below responsive level",
                "rebound / 4R potential missed comparison",
                "-$612 full loss",
                "No risk reduction; initial reaction failed and price went through stop while he was away at the gym.",
                "BE short 이후 그는 gym 전/운동 중 돌아갈 수 있는 trade를 찾았다. 하루 목표까지는 아직 부족했고, good FVG가 나오면 잡고 싶어 했다.",
                "SOL에서 significant push down 이후 fair value gap이 형성되고, 그 zone에서 long response를 기대했다. Recap에서 명확히 'long trade before gym'이라고 부른다.",
                "FVG/support response long. 주문은 전화/운동 중 관리 가능한 형태로 세팅했다.",
                "초기 technical reaction은 있었지만 momentum이 이어지지 않고 level을 통과해 stop. 운동 중 본 다른 FVG는 좋았지만 이 trade는 실패.",
                "Full stop -$612. 이후에도 하루는 +$1.5k 정도라 마지막 고품질 trade를 기다림.",
                frames(
                    p47,
                    [
                        "1094_trade5_gym_long_stopped.png",
                        "1362_recap_afternoon_be_and_gym_loss.png",
                    ],
                ),
                "SOL 18:00-19:00은 120.36 high, 118.93 low의 좁은 chop. Long response가 지속되지 못하고 stop으로 끝난 narrative와 맞다.",
                "운동/자리비움 중 trade는 반드시 stop이 명확해야 한다. Initial reaction만 있고 follow-through가 없으면 FVG long도 full loss 가능.",
                "프레임이 원거리/흐림. Direction/result는 transcript+recap 기준 high, 가격 숫자는 미확정.",
            ),
            trade(
                "p47HZv1fcUM_fd_06_trade6_sol_short_final_sr_flip_win",
                p47,
                "16",
                6,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-09",
                "23:00-23:36",
                "high_visible_overlay_plus_ohlcv",
                "19:21-20:43 + recap 23:15",
                "1161|1214|1243|1395",
                "about 116.9-117.1",
                "above resistance flip/high",
                "equal lows / lower liquidity around 114.5-115",
                "+$3,888 / about 6R",
                "Risk reduced to zero at equal lows, then stop walked down and trade taken off because it was late and daily goal was hit.",
                "하루 목표까지 약 $2.5k가 남은 밤. 시장이 크게 내려오기 시작했지만, 그는 무리하지 않고 critical resistance flip과 weakness가 맞을 때만 마지막 trade를 택했다.",
                "Downtrend forming + sell signal + support->resistance가 여러 번 겹친 zone. Candle이 previous resistance로 빠르게 fill되고 immediate response를 보이는 것을 좋은 sign으로 봤다.",
                "Flip zone short. Key levels/equal lows가 깨지면 downside room이 열리고, 1:8도 가능하지만 우선 daily goal 달성 구간을 본다.",
                "Equal lows touched 후 risk를 zero로 줄이고, 추가 push가 나오자 stop을 아래로 걸어 이익을 잠갔다. 11 PM/11:30 PM이라 overnight hold보다 realized goal을 택했다.",
                "약 6R, +$3,888. 이후 더 내려가 13R 가능성을 남겼지만, daily goal과 촬영 목적 때문에 exit.",
                frames(
                    p47,
                    [
                        "1161_trade6_final_sol_short_sr_flip_setup.png",
                        "1214_trade6_equal_lows_risk_zero.png",
                        "1243_trade6_take_profit_six_r.png",
                        "1395_recap_final_trade.png",
                    ],
                ),
                "SOL 23:02-23:04에 116.5대 breakdown, 23:25-23:32에 114.42 low. 11 PM overlay와 overnight-avoid exit narrative가 데이터와 강하게 맞다.",
                "Late session short는 support/resistance flip + sell signal + immediate response + equal-lows target. 목표 달성 후에는 더 큰 R 가능성보다 session/end-of-day risk를 우선한다.",
                "Entry exact price는 about. Time/result/setup은 strong.",
            ),
            trade(
                "mNnqjq8BzeA_fd_01_trade1_sol_long_open_fvg_win",
                mnn,
                "17",
                1,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "long",
                "2025-04-30",
                "09:59-10:35",
                "high_frame_price_plus_ohlcv",
                "03:46-06:03 + recap 20:24",
                "226|258|302|363|1224",
                "about 141.6",
                "about 140.9",
                "about 145.9 / upper continuation",
                "+$629",
                "Moved stop under recent low, then BE, then took one risk factor off because the day was bearish; rest stopped/closed small.",
                "4h daily context에서는 prior support/resistance underside가 위에 있고, 뉴스가 있는 날이라 bearish pressure를 의식했다. 그래도 9:30 이후 intraday pop/CHoCH가 있으면 첫 long을 받을 수 있었다.",
                "큰 하락 뒤 작은 pop, opposite-side response, momentum up. Change of character 이후 push의 midpoint/FVG에 주문을 두고, responsive low 아래에 stop을 둔다.",
                "FVG midpoint long. Stop은 response low 아래, target은 위쪽 continuation/gap fill 쪽.",
                "초기 bullish response 후 recent low 아래로 stop을 올리고, 곧 BE로 줄였다. 2R 이상이 열리자 extreme bearish day에 long 중이라 1 risk factor를 일부 실현했다.",
                "나머지는 trend가 이어지지 않아 종료. Recap 기준 +$629.",
                frames(
                    mnn,
                    [
                        "0226_trade1_sol_long_order_midpoint.png",
                        "0258_trade1_risk_reduce_under_low.png",
                        "0302_trade1_take_one_risk_factor.png",
                        "0363_trade1_exit_629.png",
                        "1224_recap_trade1.png",
                    ],
                ),
                "SOL 09:59 low 140.25 후 10:13-10:33에 143.26까지 반등. Frame entry 약 141.6/SL 140.9 구조와 partial win narrative가 맞다.",
                "Bearish day의 counter long은 CHoCH/FVG response가 있더라도 빠른 risk reduction과 partial이 핵심.",
                "Exact entry/SL/TP는 frame approximate.",
            ),
            trade(
                "mNnqjq8BzeA_fd_02_trade2_sol_short_funnel_small_win",
                mnn,
                "17",
                2,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-30",
                "11:30-12:20",
                "high_visible_overlay_plus_ohlcv",
                "06:29-09:05 + recap 20:40",
                "389|451|545|1240",
                "about 142.7",
                "about 143.0",
                "about 137.7 / 1h FVG high-impact target",
                "+$384",
                "At one point up about 5R, but trailed too loosely/late and only locked a little under 1R.",
                "첫 SOL long 후에도 daily bearish idea는 살아 있었다. 그는 price가 funnel/coiling 중이라 위/아래 어느 쪽으로든 break 가능성을 열어두되, sell signal이 더 논리적이라고 봤다.",
                "Top resistance + FVG + sell signal이 겹치고, price가 triangular/funnel pattern 안에서 lower break를 준비한다. 1h FVG around 137이 HTF target context.",
                "FVG midpoint/top resistance short. 아래 low break가 나오면 rest-of-session rolloff를 기대.",
                "Key level 아래 fail/retest가 나오자 stop을 trend-follow 방식으로 내리고, 1h target까지 큰 R을 열어뒀다. 하지만 price가 되돌아와 walked stop을 건드렸다.",
                "Recap 기준 +$384. Technical direction은 맞았으나 큰 move를 끝까지 잡지 못한 small win.",
                frames(
                    mnn,
                    [
                        "0389_trade2_sol_short_funnel_fvg_resistance.png",
                        "0451_trade2_fail_under_key_level.png",
                        "0545_trade2_exit_384.png",
                        "1240_recap_trade2.png",
                    ],
                ),
                "SOL 11:30대 142.1-142.8 resistance, 12:20 low 141.27. 이후 되돌림. 11:30 overlay와 short small-win 설명이 맞다.",
                "Coiling/funnel short는 top resistance FVG + sell signal + lower break가 있어야 한다. HTF target이 있어도 walk-stop에 걸리면 small win으로 끝난다.",
                "Trade2 setup frame 첫 장은 face overlay지만, 0451/recap이 차트 증거를 제공.",
            ),
            trade(
                "mNnqjq8BzeA_fd_03_trade3_sol_short_range_loss",
                mnn,
                "17",
                3,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-30",
                "13:20-13:40",
                "high_visible_overlay_plus_ohlcv",
                "09:40 + recap 21:10",
                "580|1270",
                "about 142.6",
                "about 143.3",
                "about 140.9",
                "-$584 full loss",
                "Small-range short chopped through and wicked out stop; no recovery management.",
                "두 번의 small win 후, Craig는 더 quality 있는 setup이 필요하다고 말하면서도 SOL에서 또 다른 short를 봤다.",
                "SOL이 resistance level/FVG를 다시 만들었고, 재테스트 후 failure down을 기대했다. Range가 작아 빠르게 profit을 collect하려던 아이디어였다.",
                "Small range FVG/resistance short.",
                "큰 management 없이 price가 chop through하며 stop wick-out.",
                "Recap 기준 -$584. 그는 specific analysis footage를 일부 잃었다고 말하므로, 이 행은 setup은 확보되지만 설명 depth는 다른 행보다 낮다.",
                frames(mnn, ["0580_trade3_sol_short_loss_setup.png", "1270_recap_trade3.png"]),
                "SOL 13:00-13:30은 143.25 high와 142.5대 pullback 후 다시 144대로 올라가는 구간. Short stop-out narrative와 맞다.",
                "Small range에서 FVG/resistance만으로 빠른 short를 잡으면 chop/wick stop 위험. Rule에는 low-quality range short negative example로 사용.",
                "Craig가 세부 footage를 잃었다고 했으므로 source_strength는 다른 trade보다 낮다.",
            ),
            trade(
                "mNnqjq8BzeA_fd_04_trade4_eth_long_choch_be",
                mnn,
                "17",
                4,
                "executed_trade",
                "gold_frame_data_context_ready",
                "ETHUSDT",
                "long",
                "2025-04-30",
                "13:35-14:00",
                "medium_high_frame_price_ohlcv",
                "10:20-12:00 + recap 21:28",
                "620|690|720|1288",
                "about 1772.6",
                "about 1770.3",
                "about 1788.9 / gap fill",
                "+$23 / BE",
                "Held full risk longer than earlier trades to avoid being shaken out, then trimmed risk and exited near BE when trend failed.",
                "SOL trade3 loss 후 시장이 다시 크게 push up했고, Craig는 ETH와 SOL을 비교하다 ETH setup을 선택했다.",
                "ETH가 critical resistance/wedge level 위로 CHoCH를 만들고, 그 위쪽 support/FVG로 되돌림을 주면 gap fill continuation long을 노리는 구조.",
                "Breakout 위 support/FVG long, stop은 reclaimed level 아래.",
                "처음에는 너무 빨리 BE로 옮겼다가 missed runner가 되는 것을 피하려고 full risk를 더 오래 유지했다. 이후 candle close 조건이 약해지자 stop을 recent low 아래로 올려 risk를 줄였다.",
                "결국 upper level을 깨지 못하고 trend가 실패해 +$23 BE로 종료. 직후 14:07 ETH가 1788.90까지 급등해 7R 기회를 놓쳤다고 아쉬워했다.",
                frames(
                    mnn,
                    [
                        "0620_trade4_eth_long_choch_wedge_support_fvg.png",
                        "0690_trade4_reduce_substantial_risk.png",
                        "0720_trade4_exit_small_profit_be.png",
                        "1288_recap_trade4.png",
                    ],
                ),
                "ETH 13:35-14:00은 1770대에서 CHoCH 후 버티다 14:07 high 1788.90의 god candle이 발생. BE exit 후 missed-runner 설명과 정확히 연결된다.",
                "Breakout long은 reclaim/support/FVG가 필요하지만, upper break 실패 시 BE. 너무 빠른 BE와 너무 늦은 risk trim 사이의 discretion이 관찰됨.",
                "정확한 exit minute은 자막+데이터 정렬.",
            ),
            trade(
                "mNnqjq8BzeA_fd_05_trade5_eth_short_key_level_small_win",
                mnn,
                "17",
                5,
                "executed_trade",
                "gold_frame_data_context_ready",
                "ETHUSDT",
                "short",
                "2025-04-30",
                "15:20-15:59",
                "high_visible_overlay_plus_ohlcv",
                "13:02-14:54 + recap 22:08",
                "782|838|894|1328",
                "about 1783.3",
                "about 1786.5",
                "about 1762.2",
                "+$173",
                "Reduced risk over recent high and later locked about $100; closed when ETH returned to entry and would have become full loss.",
                "ETH가 range day에서 계속 key level을 test한 뒤 마침내 아래로 break했다. Craig는 큰 selloff를 기다렸지만 계속 한 방향으로 못 가는 장세임을 의식했다.",
                "하루 동안 5번 test된 key level 아래 break, CHoCH level, pushing candle이 만든 small FVG, trend underside retest가 겹친 short.",
                "Underside retest/FVG fill short. Stop은 critical level 위.",
                "Candle close below level이 나오면 risk를 줄이겠다고 사전 선언. 이후 recent high 위로 stop을 내리고 $100 locked, swing low 아래 alert를 두며 continuation이면 더 낮출 계획.",
                "ETH가 entry로 되돌아와 +$173 close. 직후 보면 full loss였을 구조라 risk containment가 효과적이었다.",
                frames(
                    mnn,
                    [
                        "0782_trade5_eth_short_key_level_break_fvg.png",
                        "0838_trade5_risk_reduce_locked_100.png",
                        "0894_trade5_exit_173.png",
                        "1328_recap_trade5.png",
                    ],
                ),
                "ETH 15:20대 short 후 15:31 low 1775.14까지 내려갔다가 15:58-16:01에 1788 부근으로 회복. Small win close가 full loss 회피였다는 설명과 맞다.",
                "Repeated key-level break + underside retest short는 좋지만, close below swing low가 없으면 profit stop을 빠르게 당긴다.",
                "Position price exact는 about.",
            ),
            trade(
                "mNnqjq8BzeA_fd_06_trade6_eth_short_resistance_win",
                mnn,
                "17",
                6,
                "executed_trade",
                "gold_frame_data_context_ready",
                "ETHUSDT",
                "short",
                "2025-04-30",
                "16:08-17:00",
                "high_frame_price_plus_ohlcv",
                "15:28-16:30 + recap 22:58",
                "926|959|990|1378",
                "about 1803",
                "above 1808-1810 resistance high",
                "about 1775-1780 lower reset area",
                "+$1,263 / 2.666R",
                "Trailed stop down after move in favor; exited when response/flip risk appeared rather than holding for full lower target.",
                "오후에 ETH가 크게 push up했고, Craig는 이전 low area/session high 부근이 resistance로 작동할 수 있는 구간을 찾았다.",
                "Prior lows가 retest된 area + session high + sell signal + dying volume. 급등 후 weakness가 나타나면 short로 rolloff를 기대했다.",
                "Sell signal 후 resistance area에서 short. Stop은 급등 high 위, target은 middle/lower reset area.",
                "ETH가 내려오기 시작하자 trend-follow 방식으로 stop을 이동해 full risk factor 이상을 잠갔다. 더 큰 move를 원했지만 flip response가 나오자 2.666R을 확보.",
                "Recap 기준 +$1,263.",
                frames(
                    mnn,
                    [
                        "0926_trade6_eth_short_prior_lows_resistance.png",
                        "0959_trade6_trend_follow_short.png",
                        "0990_trade6_exit_1263.png",
                        "1378_recap_trade6.png",
                    ],
                ),
                "ETH 16:08 current 1800-1803 frame와 데이터가 일치. 16:14 high 1809.19 후 16:57-17:03에 1793-1796으로 밀려 short MFE와 exit 구조가 맞다.",
                "Resistance short는 prior lows/session high retest + sell signal + volume fading. 큰 target보다 response/flip 위험이 커지면 locked profit으로 종료.",
                "Stop exact price는 frame에서 작아 range로 기록.",
            ),
            trade(
                "mNnqjq8BzeA_fd_07_trade7_eth_long_dinner_runner_win",
                mnn,
                "17",
                7,
                "executed_trade",
                "gold_frame_data_context_ready",
                "ETHUSDT",
                "long",
                "2025-04-30",
                "17:00-17:20",
                "medium_high_frame_recap_ohlcv",
                "17:00-18:40 + recap 23:30",
                "1020|1094|1120|1410",
                "about 1792-1794",
                "about 1790-1791",
                "upper break / about 1799-1802 planned area",
                "+$2,384 / 5.7R",
                "Reduced to BE while away, then walked stop up under breakout level and took profit on push because daily goal was reached.",
                "여러 small win/BE 뒤 하루 내내 방어만 하던 상태에서, Craig는 gym/dinner 동안 돌릴 수 있는 setup을 찾았다. 계좌는 이미 약 +$3k였고 capital preservation을 강조했다.",
                "ETH가 zone 안에서 여러 번 level을 test한 뒤 top level을 break할 가능성. Recap frame은 ETHUSDT 1m long box와 narrowing structure를 보여준다.",
                "Zone long. Stop은 tested level 아래, 목표는 top break 후 upper push.",
                "처음에는 entry 부근에서 머물렀지만 +$800 정도가 보이자 BE로 줄였다. 이후 high break가 나오자 stop을 계속 올렸고, 더 pop할 수 있으면 trail하려 했다.",
                "+$2,384, 5.7R. 그는 약 한 시간짜리 trade로 day goal을 넘겼다고 정리했다.",
                frames(
                    mnn,
                    [
                        "1020_trade7_gym_dinner_trade_risk_defense.png",
                        "1094_trade7_breaking_high_manage.png",
                        "1120_trade7_exit_2384.png",
                        "1410_recap_trade7.png",
                    ],
                ),
                "ETH는 17:00 low 1793.00 후 17:20 high 1799.93. Recap long box의 entry zone과 5.7R runner narrative가 이 구간과 가장 잘 맞다.",
                "Choppy day에서 좋은 zone long이 top break를 만들면 BE 방어 후 trail. 큰 winner는 기다리되, 목표 달성 시 realized exit.",
                "Video transcript의 '1802'는 시간보다 price/profit OCR 가능성이 높아 market time으로 쓰지 않음.",
            ),
            trade(
                "mNnqjq8BzeA_fd_08_trade8_sol_short_overnight_be",
                mnn,
                "17",
                8,
                "executed_trade",
                "gold_frame_data_context_ready",
                "SOLUSDT",
                "short",
                "2025-04-30/2025-05-01",
                "23:50-overnight",
                "high_visible_overlay_plus_next_day_ohlcv",
                "19:15-20:13 + recap 23:52",
                "1155|1188|1432",
                "about 148.6-148.8",
                "moved to BE",
                "near equal lows / below 147.9 area",
                "+$14 / BE",
                "Risk reduced to zero before sleep; price came close to target overnight but reversed and touched BE.",
                "ETH big long 후에도 market이 끝까지 밀어붙이는 uptrend를 만들었다. 그는 마지막 trade로, massive uptrend에서 weakness/rolloff가 나오는지만 보겠다고 했다.",
                "SOL의 uptrend break, level break, retest entry. Recap에서는 candle이 entry에 'beautifully' contact하고 selloff가 나왔다고 말한다. Target은 equal lows 부근/아래.",
                "Weakness confirmation 후 retest short. Stop은 BE로 옮겨 overnight risk를 제거.",
                "11:50 PM에 risk zero, target은 equal lows 거의 아래. 잠자는 동안 추가 reduction은 못 했고, 다음날 확인 시 가격이 되돌아와 BE touch.",
                "결과 +$14로 book상 BE. 전체 일 수익 +$4,286.",
                frames(
                    mnn,
                    [
                        "1155_trade8_last_trade_rolloff_setup.png",
                        "1188_trade8_1150_risk_zero_overnight.png",
                        "1432_recap_trade8.png",
                    ],
                ),
                "SOL 2025-04-30 22:37 high 149.58 후 23:50대 148.6 부근. 2025-05-01 00:32 low 147.91까지 내려갔다가 09:23 high 152.48로 반등해, 'target 근접 후 BE' 설명과 맞다.",
                "Overnight short는 risk-free일 때만 허용. Target 근처까지 가도 sleep 상태라 active trail이 불가능하면 BE 회귀를 받아들인다.",
                "Exact TP가 147.91보다 약간 아래였을 가능성이 있어 'near target'으로 기록.",
            ),
        ]
    )

    rules.extend(
        [
            rule(
                "p47_rule_01_news_open_fvg_runner_long",
                "p47HZv1fcUM_fd_01_trade1_sol_long_news_open_win",
                "news_open_displacement_fvg_long",
                "Bearish macro/news day라도 NY open 후 displacement 방향이 위이고 prior resistance가 support로 flip되면 long 허용.",
                "09:30 displacement through level -> FVG left behind -> trend/overside retest.",
                "FVG/support retest에 fixed-risk long.",
                "Retest zone 및 swing low가 깨지면 exit; trendline touches가 잦아지면 runner thesis 약화.",
                "Recent high close 후 BE, 1:4 도달 후 tactical hold, trend weakness 시 2.5R 이상 lock.",
                "2.618 extension/large R 가능성을 보되 trend weakness가 먼저면 trail exit.",
                "뉴스 급등/하락에 맞서지 말고 실제 displacement 반응을 본 뒤 진입.",
                "ny_open_displacement; fvg_retest; resistance_to_support; trend_touch_frequency; mfe_r_multiple; trail_stop_distance",
                "strong_context_medium_price",
            ),
            rule(
                "p47_rule_02_underside_retest_short_be",
                "p47HZv1fcUM_fd_02_trade2_sol_short_underside_be",
                "trend_break_underside_fvg_short",
                "Long runner exit 후 same trendline이 깨지면 short flip 후보지만 market momentum이 calm하면 confirmation 필요.",
                "Trendline break -> underside retest into FVG/resistance -> lower level break attempt.",
                "Underside/FVG retest에서 short.",
                "Lower low 실패 후 entry 회복하면 BE exit.",
                "Lower level break가 나오면 BE로 줄임.",
                "Downside continuation target은 lower blue/key level.",
                "Initial response만으로 bearish day를 가정하지 말 것.",
                "trendline_break; underside_retest; fvg_overlap; lower_level_close; be_reversal",
                "strong_context_medium_price",
            ),
            rule(
                "p47_rule_03_execution_anomaly_exclude",
                "p47HZv1fcUM_fd_03_trade3_sol_short_fatfinger_reentry_loss",
                "execution_anomaly_negative_example",
                "News pump 직후 exposure 욕구가 강하고 setup quality가 낮을 때.",
                "Pump into critical retest level; intended fade short, but duplicate submissions create oversize.",
                "Core rule model에서는 duplicate-entry를 제외하고 intended re-entry만 low-quality short sample로 사용.",
                "Oversize 발견 즉시 flatten; normal re-entry는 stop above retest.",
                "Anomaly PnL은 model target에서 제외.",
                "None for anomaly; intended trade sought afternoon selloff.",
                "Execution mistake를 strategy edge로 학습하지 말 것.",
                "news_pump; duplicate_order_flag; intended_size_vs_actual; retest_short_quality; sideways_duration",
                "strong_context_not_rule_core",
            ),
            rule(
                "p47_rule_04_afternoon_break_fvg_be_short",
                "p47HZv1fcUM_fd_04_trade4_sol_short_afternoon_fvg_be",
                "afternoon_trend_break_fvg_short",
                "오후 news pump 이후 trend가 깨지고 FVG/CHoCH가 생길 때만 short continuation.",
                "Afternoon trend breakdown -> FVG -> underside retest -> lower close.",
                "FVG/underside entry short.",
                "Stop above underside/retest; almost-stop tolerated only if structure intact.",
                "Lower close after entry triggers BE/risk-free.",
                "Continuation target lower levels, but BE if follow-through fails.",
                "자리비움 전 trade는 risk-free 전환 기준이 명확해야 함.",
                "afternoon_trend_break; choch; fvg_entry; lower_close; be_stop_hit",
                "medium_strong_context",
            ),
            rule(
                "p47_rule_05_gym_fvg_long_loss",
                "p47HZv1fcUM_fd_05_trade5_sol_long_gym_loss",
                "fvg_reaction_long_negative",
                "Significant push down 후 FVG response long은 가능하나, 자리비움 중에는 hard stop 필수.",
                "Push down -> bullish FVG/technical response -> long before gym.",
                "FVG/support response에서 long.",
                "Responsive level 아래 stop; no manual rescue while away.",
                "Initial reaction만 있고 momentum이 죽으면 full stop 가능.",
                "Rebound/4R potential only if follow-through appears.",
                "운동/외출 중 active management가 필요한 setup은 quality discount.",
                "fvg_after_push_down; initial_response; follow_through_failure; away_from_desk_flag",
                "medium_context_result_strong",
            ),
            rule(
                "p47_rule_06_late_sr_flip_short_goal_exit",
                "p47HZv1fcUM_fd_06_trade6_sol_short_final_sr_flip_win",
                "late_session_sr_flip_short",
                "밤 session에서 downtrend와 weakness가 명확하고 support/resistance flip이 겹칠 때 short.",
                "Support->resistance multi-touch zone + sell signal + immediate rejection.",
                "Retest/fill into prior resistance에서 short.",
                "Resistance high 위 회복 시 invalidation; equal lows touch 후 BE.",
                "Equal lows touch -> BE; further push -> walk stop down; daily goal hit -> realize.",
                "Equal lows just below; larger 13R potential secondary.",
                "Late night/overnight risk가 커지면 runner보다 realized goal 우선.",
                "sr_flip_count; sell_signal; immediate_response; equal_lows_distance; time_of_day; goal_reached",
                "strong_frame_ohlcv",
            ),
            rule(
                "mnn_rule_01_bearish_day_counter_long_partial",
                "mNnqjq8BzeA_fd_01_trade1_sol_long_open_fvg_win",
                "bearish_day_choch_fvg_counter_long",
                "Daily bearish pressure가 있어도 9:30 이후 CHoCH/FVG response가 있으면 short-term long 가능.",
                "Pop -> opposite-side response -> CHoCH -> midpoint FVG pullback.",
                "FVG midpoint long, stop below responsive low.",
                "Responsive low slice-through이면 no hold.",
                "Recent low trail -> BE -> partial one risk factor when 2R+ and macro bearish.",
                "Upper continuation/gap fill, but partial before full target.",
                "Extreme bearish day counter-long은 빠른 partial/risk reduction 없이 오래 들지 않음.",
                "choch; fvg_midpoint; responsive_low; bearish_day_flag; partial_at_r",
                "strong_frame_ohlcv",
            ),
            rule(
                "mnn_rule_02_funnel_top_fvg_short",
                "mNnqjq8BzeA_fd_02_trade2_sol_short_funnel_small_win",
                "coiling_funnel_resistance_short",
                "Price가 funnel/coiling이고 top resistance/FVG/sell signal이 겹칠 때 downside break를 선제 short.",
                "Top resistance + FVG + sell signal -> break under low expectation.",
                "Midpoint FVG/top zone short.",
                "Upside break이면 short thesis 폐기, possible long support flip 후보로 전환.",
                "Trend-follow stop down; cannot lose after lower break.",
                "HTF 1h FVG/support-resistance around 137 as stretch target.",
                "큰 HTF target이 있어도 retrace stop에 걸리면 small win 수용.",
                "funnel_slope; top_resistance_touch; sell_signal; lower_break; htf_fvg_target_distance",
                "strong_context",
            ),
            rule(
                "mnn_rule_03_small_range_short_negative",
                "mNnqjq8BzeA_fd_03_trade3_sol_short_range_loss",
                "small_range_fvg_short_loss",
                "Small range에서 resistance/FVG만 보고 빠른 short를 잡는 setup은 wick-out 위험.",
                "Small FVG into resistance retest.",
                "Short at retest hoping quick failure.",
                "Stop above range/resistance wick.",
                "No room for management if chop-through occurs.",
                "Quick profit only; no runner context.",
                "Range가 너무 작으면 risk/reward와 wick risk를 discount.",
                "range_height; fvg_size; resistance_distance; wick_stop_frequency",
                "medium_context",
            ),
            rule(
                "mnn_rule_04_eth_breakout_fvg_long_be",
                "mNnqjq8BzeA_fd_04_trade4_eth_long_choch_be",
                "eth_breakout_support_fvg_long",
                "ETH가 critical level/wedge 위로 reclaim하면 gap fill long 후보.",
                "CHoCH over resistance -> support/FVG retest.",
                "Retest support/FVG long.",
                "Reclaimed level 실패/upper break failure 시 BE.",
                "초기에는 full risk를 조금 더 유지하되, close weakness 후 risk trim.",
                "Gap fill/upper impulse.",
                "Upper level break 실패가 보이면 missed runner risk보다 capital preservation.",
                "choch_over_level; wedge_break; support_retest; upper_break_failure; missed_runner_after_exit",
                "strong_context_medium_price",
            ),
            rule(
                "mnn_rule_05_eth_repeated_level_break_short",
                "mNnqjq8BzeA_fd_05_trade5_eth_short_key_level_small_win",
                "repeated_level_break_underside_short",
                "여러 번 test된 level이 아래로 깨지고 underside retest/FVG가 있으면 short.",
                "Five-test key level break -> small FVG -> underside retest.",
                "FVG/underside short, stop above critical level.",
                "Close below level 실패 또는 entry reclaim 시 profit close.",
                "Close below level -> stop over high -> lock small profit.",
                "Lower swing/continuation target.",
                "Choppy day에는 full target보다 full loss 회피가 우선.",
                "test_count; level_break; fvg_size; close_below; entry_reclaim; avoided_full_loss",
                "strong_frame_ohlcv",
            ),
            rule(
                "mnn_rule_06_eth_prior_lows_resistance_short",
                "mNnqjq8BzeA_fd_06_trade6_eth_short_resistance_win",
                "prior_lows_session_high_resistance_short",
                "Market push up after range; prior lows/session high area에서 weakness와 sell signal이 나오면 short.",
                "Prior lows retest + session high + dying volume + sell signal.",
                "Resistance area short after signal.",
                "Stop above high/resistance cluster.",
                "Move in favor -> trail over structure; response flip -> realize 2R+.",
                "Middle/lower reset area; full lower target optional.",
                "강한 pump 직후 short는 high stop을 넉넉히 보되, flip response가 나오면 profit을 지킨다.",
                "prior_low_cluster; session_high_distance; volume_decay; sell_signal; trail_stop; flip_response",
                "strong_frame_ohlcv",
            ),
            rule(
                "mnn_rule_07_eth_zone_long_runner",
                "mNnqjq8BzeA_fd_07_trade7_eth_long_dinner_runner_win",
                "tested_zone_breakout_long_runner",
                "Choppy day 후 tested zone에서 top break가 나오면 day's main winner가 될 수 있음.",
                "Zone tests multiple times -> top level break -> push.",
                "Long inside/near zone, stop below tested level.",
                "Zone low break invalidates.",
                "BE while away; breakout 후 stop under new level; goal reached exit.",
                "Upper push/5R+ runner.",
                "Away-from-desk trade는 BE 전환 후에만 방치.",
                "zone_test_count; top_break; be_before_away; trail_under_breakout; r_multiple_exit",
                "strong_context_medium_price",
            ),
            rule(
                "mnn_rule_08_sol_overnight_uptrend_rolloff_short",
                "mNnqjq8BzeA_fd_08_trade8_sol_short_overnight_be",
                "overnight_uptrend_weakness_short",
                "Massive uptrend 마지막에 weakness/break가 나오고 risk-free 전환이 가능할 때만 overnight short.",
                "Uptrend break -> level break -> retest fill -> selloff toward equal lows.",
                "Retest short after weakness confirmation.",
                "BE stop before sleep; target not reached means no active rescue.",
                "Risk zero before overnight, accept BE if target near-miss reverses.",
                "Equal lows/lower liquidity.",
                "잠자는 동안 trail할 수 없으면 near-TP라도 BE 회귀 가능성을 감수.",
                "uptrend_slope; break_level; retest_fill_quality; equal_lows_distance; overnight_flag; next_day_low_vs_tp",
                "strong_frame_nextday_ohlcv",
            ),
        ]
    )

    write_csv(OUT_SESSIONS, session_fields, sessions)
    write_csv(OUT_TRADES, trade_fields, trades)
    write_csv(OUT_RULES, rule_fields, rules)

    lines = [
        "# Frame + Data Validated Batch: Scope 16-17",
        "",
        "Processed exactly two additional videos after the first frame+data pass.",
        "",
        "## Videos",
        "",
        "- `p47HZv1fcUM` / scope 16 / `Live Day Trading (I DID NOT EXPECT TO WIN)` / 6 decision rows",
        "- `mNnqjq8BzeA` / scope 17 / `Live Day Trading (THIS DAY WAS BORING BUT WORKED)` / 8 decision rows",
        "",
        "## Outputs",
        "",
        f"- session map: `{OUT_SESSIONS.relative_to(ROOT).as_posix()}`",
        f"- trade context queue: `{OUT_TRADES.relative_to(ROOT).as_posix()}`",
        f"- rule seed queue: `{OUT_RULES.relative_to(ROOT).as_posix()}`",
        f"- p47 frames: `data/source/craig_frames/browser_review/p47HZv1fcUM_frame_data_pass/`",
        f"- mNn frames: `data/source/craig_frames/browser_review/mNnqjq8BzeA_frame_data_pass/`",
        "",
        "## Cumulative Counts",
        "",
        f"- sessions: {len(sessions)}",
        f"- trade/decision contexts: {len(trades)}",
        f"- rule seeds: {len(rules)}",
        "",
        "## Method Notes",
        "",
        "- Captured selected setup/entry/management/recap frames from logged-in YouTube playback.",
        "- Used visible overlays and TradingView symbols/timeframes to confirm chart context.",
        "- Used Binance 1m NY-session OHLCV for 2025-04-09 SOL, 2025-04-30 SOL/ETH, and 2025-05-01 SOL overnight validation.",
        "- Rows with exact price not safely OCR-readable keep `about` values and explain uncertainty.",
    ]
    OUT_SUMMARY.parent.mkdir(parents=True, exist_ok=True)
    OUT_SUMMARY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT_TRADES)
    print(OUT_RULES)
    print(OUT_SUMMARY)


if __name__ == "__main__":
    main()
